// artifacts/roommate-tasker/src/pages/Personal.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { user, authLoading } from '../lib/auth';
  import { navigate } from '../lib/router';
  import { findHouseByUser, subscribeToHouse, overrideCurrentAssignee, completeTaskInFirestore } from '../lib/firestore';
  import { getCurrentAssigneeUid, getUrgency, getMemberByUid } from '../lib/schedule';
  import type { HouseData } from '../lib/types';
  import TaskCard from '../components/TaskCard.svelte';
  import OverrideModal from '../components/OverrideModal.svelte';

  let initialized = false;
  let houseId: string | null = null;
  let data: HouseData | null = null;
  let loading = true;
  let toast: string | null = null;
  let overrideTaskId: string | null = null;
  let unsub: (() => void) | null = null;

  $: {
    if (!$authLoading) {
      if (!$user) { navigate('/login'); }
      else if (!initialized) { initialized = true; init(); }
    }
  }

  async function init() {
    try {
      const house = await findHouseByUser($user!.uid);
      if (!house) { navigate('/join'); return; }
      houseId = house.id;
      unsub = subscribeToHouse(house.id, (houseData) => {
        if (houseData) data = houseData;
        loading = false;
      });
    } catch (err) { console.error('Personal init error:', err); loading = false; }
  }

  function showToast(msg: string) { toast = msg; setTimeout(() => { toast = null; }, 3000); }

  async function handleComplete(taskId: string) {
    if (!houseId || !data || !$user) return;
    const completedByName = getMemberByUid(data.members, $user.uid)?.displayName || $user.displayName || 'Unknown';
    await completeTaskInFirestore(houseId, taskId, data, $user.uid, completedByName);
    showToast('✅ Task Completed!');
  }

  async function handleOverride(swapWithUid: string) {
    if (!houseId || !data || !overrideTaskId) return;
    await overrideCurrentAssignee(houseId, overrideTaskId, data, swapWithUid);
    overrideTaskId = null;
  }

  onDestroy(() => { if (unsub) unsub(); });

  $: isAdmin = data ? data.adminUid === $user?.uid : false;
  $: myTasks = (data && $user) ? data.tasks.filter((t) => getCurrentAssigneeUid(t) === $user!.uid) : [];
  $: overdueTasks = myTasks.filter((t) => getUrgency(t) === 'overdue');
  $: todayTasks = myTasks.filter((t) => getUrgency(t) === 'due-today');
  $: upcomingTasks = myTasks.filter((t) => getUrgency(t) === 'upcoming');
  $: completedToday = (() => {
    if (!data || !$user) return [];
    const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0);
    return data.tasks.flatMap(task =>
      (task.history || [])
        .filter(h => h.uid === $user!.uid && new Date(h.date) >= todayStart)
        .map(h => ({ ...task, completionDate: h.date }))
    );
  })();
  $: overrideTask = overrideTaskId && data ? data.tasks.find((t) => t.id === overrideTaskId) : null;
</script>

{#if $authLoading || loading}
  <div class="loadingPage"><div class="spinner"></div><p>Loading My Tasks...</p></div>
{:else if data && $user}
  <div class="pageWrapper" style="max-width:560px">
    {#if toast}<div class="toast">{toast}</div>{/if}

    <header class="pageHeader">
      <h1 class="pageTitle">👤 My Tasks</h1>
    </header>

    {#if overdueTasks.length > 0}
      <div class="section">
        <h2 class="sectionTitle">Overdue Task</h2>
        <div class="cardGrid">
          {#each overdueTasks as task (task.id)}
            <TaskCard {task} members={data.members} currentUserUid={$user.uid} {isAdmin}
              onComplete={handleComplete} onOverride={(id) => { overrideTaskId = id; }} />
          {/each}
        </div>
      </div>
    {/if}

    {#if todayTasks.length > 0}
      <div class="section">
        <h2 class="sectionTitle">Today's Task (My Turn)</h2>
        <div class="cardGrid">
          {#each todayTasks as task (task.id)}
            <TaskCard {task} members={data.members} currentUserUid={$user.uid} {isAdmin}
              onComplete={handleComplete} onOverride={(id) => { overrideTaskId = id; }} />
          {/each}
        </div>
      </div>
    {/if}

    {#if upcomingTasks.length > 0}
      <div class="section">
        <h2 class="sectionTitle">Upcoming Task</h2>
        <div class="cardGrid">
          {#each upcomingTasks as task (task.id)}
            <TaskCard {task} members={data.members} currentUserUid={$user.uid} {isAdmin}
              onComplete={handleComplete} onOverride={(id) => { overrideTaskId = id; }} />
          {/each}
        </div>
      </div>
    {/if}

    {#if completedToday.length > 0}
      <div class="section">
        <h2 class="sectionTitle">Completed Task (Celebrating)</h2>
        <div class="completedList">
          {#each completedToday as t, idx (idx)}
            <div class="completedCard">
              <div class="checkCircle">✓</div>
              <div class="completedInfo">
                <h3 class="completedTitle">{t.name}</h3>
                <p class="completedSub">Completed today</p>
              </div>
            </div>
          {/each}
        </div>
      </div>
    {/if}

    {#if myTasks.length === 0 && completedToday.length === 0}
      <div class="emptyState">
        <span class="emptyIcon">🎉</span>
        <p>You are all caught up for today!</p>
      </div>
    {/if}

    {#if overrideTask}
      <OverrideModal
        task={overrideTask} members={data.members}
        onSwap={handleOverride} onClose={() => { overrideTaskId = null; }}
      />
    {/if}
  </div>
{/if}

<style>
  .completedList { display: flex; flex-direction: column; gap: 8px; }

  .completedCard {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 14px 16px;
    background: #f0fdf4;
    border: 1px solid #bbf7d0;
    border-radius: var(--r-md);
  }

  .checkCircle {
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background: #16a34a;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 700;
    font-size: 1rem;
    flex-shrink: 0;
  }

  .completedTitle { font-weight: 700; font-size: 0.9rem; color: #15803d; }
  .completedSub { font-size: 0.75rem; color: #166534; margin-top: 2px; }
</style>

// src/app/personal/page.tsx
'use client';

import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth';
import { HouseData, Task } from '@/lib/types';
import { findHouseByUser, subscribeToHouse, overrideCurrentAssignee, completeTaskInFirestore } from '@/lib/firestore';
import { getCurrentAssigneeUid, getUrgency, getMemberByUid } from '@/lib/schedule';
import TaskCard from '@/components/TaskCard';
import OverrideModal from '@/components/OverrideModal';
import styles from './personal.module.css';

export default function PersonalPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const [houseId, setHouseId] = useState<string | null>(null);
  const [data, setData] = useState<HouseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState<string | null>(null);
  const [overrideTaskId, setOverrideTaskId] = useState<string | null>(null);

  useEffect(() => {
    if (authLoading) return;
    if (!user) { router.push('/login'); return; }

    let unsub: (() => void) | null = null;

    const init = async () => {
      try {
        const house = await findHouseByUser(user.uid);
        if (!house) { router.push('/join'); return; }

        setHouseId(house.id);
        unsub = subscribeToHouse(house.id, (houseData) => {
          if (houseData) {
            setData(houseData);
          }
          setLoading(false);
        });
      } catch (err) {
        console.error('Personal init error:', err);
        setLoading(false);
      }
    };

    init();
    return () => { if (unsub) unsub(); };
  }, [user, authLoading, router]);

  const handleComplete = useCallback(async (taskId: string) => {
    if (!houseId || !data || !user) return;
    const completedByName = getMemberByUid(data.members, user.uid)?.displayName || user.displayName || 'Unknown';
    await completeTaskInFirestore(houseId, taskId, data, user.uid, completedByName);
    setToast('✅ Task Completed!');
    setTimeout(() => setToast(null), 3000);
  }, [houseId, data, user]);

  const handleOverride = useCallback(async (swapWithUid: string) => {
    if (!houseId || !data || !overrideTaskId) return;
    await overrideCurrentAssignee(houseId, overrideTaskId, data, swapWithUid);
    setOverrideTaskId(null);
  }, [houseId, data, overrideTaskId]);

  if (authLoading || loading) {
    return <div className="loadingPage"><div className="spinner" /><p>Loading My Tasks...</p></div>;
  }
  if (!data || !user) return null;

  const isAdmin = data.adminUid === user.uid;

  // Filter ONLY My Tasks
  const myTasks = data.tasks.filter((t) => getCurrentAssigneeUid(t) === user.uid);

  // Group by Urgency
  const overdueTasks = myTasks.filter((t) => getUrgency(t) === 'overdue');
  const todayTasks = myTasks.filter((t) => getUrgency(t) === 'due-today');
  const upcomingTasks = myTasks.filter((t) => getUrgency(t) === 'upcoming');

  // Pull History Completed Today
  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);

  const completedToday = data.tasks.flatMap(task => 
    (task.history || [])
      .filter(h => h.uid === user.uid && new Date(h.date) >= todayStart)
      .map(h => ({ ...task, completionDate: h.date }))
  );

  return (
    <div className="pageWrapper" style={{ maxWidth: '560px' }}> {/* Keep single column for mobile list mockup feel */}
      {toast && <div className="toast">{toast}</div>}

      <header className={styles.header}>
        <h1 className={styles.title}>Roommate Tasker</h1>
      </header>

      {overdueTasks.length > 0 && (
        <div className={styles.section}>
          <h2 className={styles.sectionHeader}>Overdue Task</h2>
          <div className={styles.list}>
            {overdueTasks.map(t => (
              <TaskCard key={t.id} task={t} members={data.members} currentUserUid={user.uid} isAdmin={isAdmin} onComplete={handleComplete} onOverride={setOverrideTaskId} />
            ))}
          </div>
        </div>
      )}

      {todayTasks.length > 0 && (
        <div className={styles.section}>
          <h2 className={styles.sectionHeader}>Today's Task (My Turn)</h2>
          <div className={styles.list}>
            {todayTasks.map(t => (
              <TaskCard key={t.id} task={t} members={data.members} currentUserUid={user.uid} isAdmin={isAdmin} onComplete={handleComplete} onOverride={setOverrideTaskId} />
            ))}
          </div>
        </div>
      )}

      {upcomingTasks.length > 0 && (
        <div className={styles.section}>
          <h2 className={styles.sectionHeader}>Upcoming Task</h2>
          <div className={styles.list}>
            {upcomingTasks.map(t => (
              <TaskCard key={t.id} task={t} members={data.members} currentUserUid={user.uid} isAdmin={isAdmin} onComplete={handleComplete} onOverride={setOverrideTaskId} />
            ))}
          </div>
        </div>
      )}

      {completedToday.length > 0 && (
        <div className={styles.section}>
          <h2 className={styles.sectionHeader}>Completed Task (Celebrating)</h2>
          <div className={styles.list}>
            {completedToday.map((t, idx) => (
              <div key={idx} className={styles.completedCard}>
                <div className={styles.checkCircle}>
                  <span>✓</span>
                </div>
                <div className={styles.completedInfo}>
                  <h3 className={styles.completedTitle}>{t.name}</h3>
                  <p className={styles.completedSubtitle}>Completed today</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {myTasks.length === 0 && completedToday.length === 0 && (
        <div className="emptyState">
          <span className="emptyIcon">🎉</span>
          <p>You are all caught up for today!</p>
        </div>
      )}

      {overrideTaskId && (
        <OverrideModal
          task={data.tasks.find((t) => t.id === overrideTaskId)!} members={data.members}
          onSwap={handleOverride} onClose={() => setOverrideTaskId(null)}
        />
      )}
    </div>
  );
}
