// src/pages/Join.svelte
<script lang="ts">
  import { user, authLoading } from '../lib/auth';
  import { navigate } from '../lib/router';
  import { createGroup, joinGroup } from '../lib/api';

  let mode: 'join' | 'create' = 'join';
  let code = '';
  let groupName = '';
  let error = '';
  let submitting = false;

  $: if (!$authLoading && !$user) navigate('/login');

  async function handleJoin() {
    if (!code.trim()) { error = 'Please enter an invite code'; return; }
    submitting = true;
    error = '';
    const group = await joinGroup(code.trim());
    submitting = false;
    if (group) {
      navigate('/');
    } else {
      error = 'Invalid invite code or unable to join group.';
    }
  }

  async function handleCreate() {
    if (!groupName.trim()) { error = 'Please enter a group name'; return; }
    submitting = true;
    error = '';
    const group = await createGroup(groupName.trim());
    submitting = false;
    if (group) {
      navigate('/');
    } else {
      error = 'Failed to create group. Please try again.';
    }
  }
</script>

{#if $authLoading}
  <div class="loadingPage"><div class="spinner"></div><p>Loading...</p></div>
{:else if $user}
  <div class="pageWrapper">
    <header class="pageHeader">
      <h1 class="pageTitle">🔄 Welcome to TaskSync</h1>
      <p class="pageSubtitle">Join an existing group or start a new one</p>
    </header>

    <div class="modeToggle">
      <button class="toggleBtn {mode === 'join' ? 'active' : ''}" on:click={() => { mode = 'join'; error = ''; }}>
        Join Group
      </button>
      <button class="toggleBtn {mode === 'create' ? 'active' : ''}" on:click={() => { mode = 'create'; error = ''; }}>
        Create Group
      </button>
    </div>

    {#if error}
      <div class="errorBanner">{error}</div>
    {/if}

    {#if mode === 'join'}
      <div class="card">
        <label for="code" class="inputLabel">6-Character Invite Code</label>
        <input
          id="code"
          type="text"
          bind:value={code}
          placeholder="e.g. VTSEGF"
          class="inputField"
          maxlength="6"
        />
        <button class="btnPrimary" on:click={handleJoin} disabled={submitting}>
          {submitting ? 'Joining...' : 'Join Group'}
        </button>
      </div>
    {:else}
      <div class="card">
        <label for="groupName" class="inputLabel">Group / Apartment Name</label>
        <input
          id="groupName"
          type="text"
          bind:value={groupName}
          placeholder="e.g. 88 Gardner St Apt 33"
          class="inputField"
        />
        <button class="btnPrimary" on:click={handleCreate} disabled={submitting}>
          {submitting ? 'Creating...' : 'Create Group'}
        </button>
      </div>
    {/if}
  </div>
{/if}

<style>
  .modeToggle { display: flex; gap: 8px; margin-bottom: 20px; }
  .toggleBtn {
    flex: 1;
    padding: 10px;
    border-radius: 12px;
    border: 1px solid var(--border);
    background: white;
    font-weight: 700;
    cursor: pointer;
  }
  .toggleBtn.active { background: var(--accent-bg); color: var(--accent); border-color: var(--accent-border); }
  .card { background: white; border-radius: 16px; padding: 20px; border: 1px solid var(--border); display: flex; flex-direction: column; gap: 12px; }
  .inputLabel { font-size: 0.8rem; font-weight: 700; color: var(--text-secondary); }
  .inputField { padding: 12px; border-radius: 10px; border: 1px solid var(--border); font-size: 1rem; }
  .btnPrimary { padding: 12px; background: var(--accent); color: white; border: none; border-radius: 10px; font-weight: 700; cursor: pointer; }
  .errorBanner { background: #fee2e2; color: #991b1b; padding: 10px 14px; border-radius: 10px; font-size: 0.85rem; font-weight: 600; margin-bottom: 12px; }
</style>

// artifacts/roommate-tasker/src/app/join/page.tsx
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { useAuth } from '@/lib/auth';
import { HouseData } from '@/lib/types';
import { joinHouse, createHouse, findAllHousesByUser } from '@/lib/firestore';
import styles from './join.module.css';

export default function JoinPage() {
    const { user, loading: authLoading } = useAuth();
    const [, navigate] = useLocation();
    const [mode, setMode] = useState<'join' | 'create'>('join');
    const [code, setCode] = useState('');
    const [houseName, setHouseName] = useState('');
    const [error, setError] = useState('');
    const [submitting, setSubmitting] = useState(false);
    const [popularHouses, setPopularHouses] = useState<{ id: string; data: HouseData }[]>([]);

    useEffect(() => {
        if (!authLoading && !user) navigate('/login');
        if (user) {
            findAllHousesByUser(user.uid).then(setPopularHouses).catch(() => { });
        }
    }, [user, authLoading]);

    if (authLoading || !user) {
        return <div className="loadingPage"><div className="spinner" /><p>Loading...</p></div>;
    }

    const handleJoin = async (inviteCode?: string) => {
        const codeToUse = inviteCode || code.trim();
        if (!codeToUse) { setError('Enter an invite code'); return; }
        setSubmitting(true);
        setError('');
        try {
            const houseId = await joinHouse(codeToUse, user.uid, user.displayName || 'User', user.email || '', user.photoURL);
            if (!houseId) { setError('House not found. Check the code.'); setSubmitting(false); return; }
            navigate('/');
        } catch { setError('Something went wrong.'); setSubmitting(false); }
    };

    const handleCreate = async () => {
        setSubmitting(true);
        setError('');
        try {
            await createHouse(user.uid, user.displayName || 'User', user.email || '', user.photoURL, houseName.trim());
            navigate('/');
        } catch { setError('Something went wrong.'); setSubmitting(false); }
    };

    return (
        <div className="pageWrapper">
            <header className="pageHeader">
                <h1 className="pageTitle">🏠 Get Started</h1>
                <p className="pageSubtitle">Join an existing house or create a new one</p>
            </header>

            <div className={styles.toggle}>
                <button className={`${styles.toggleBtn} ${mode === 'join' ? styles.toggleActive : ''}`} onClick={() => { setMode('join'); setError(''); }}>
                    Join House
                </button>
                <button className={`${styles.toggleBtn} ${mode === 'create' ? styles.toggleActive : ''}`} onClick={() => { setMode('create'); setError(''); }}>
                    Create House
                </button>
            </div>

            {mode === 'join' ? (
                <div className="section">
                    <div className="inputGroup">
                        <label className="inputLabel">Invite Code</label>
                        <input
                            className="inputField"
                            placeholder="e.g. ABC123"
                            value={code}
                            onChange={(e) => setCode(e.target.value.toUpperCase())}
                            onKeyDown={(e) => e.key === 'Enter' && handleJoin()}
                            maxLength={8}
                            style={{ textTransform: 'uppercase', letterSpacing: '0.15em', fontWeight: 700 }}
                        />
                    </div>
                    {error && <p className={styles.error}>{error}</p>}
                    <button className="btnPrimary" onClick={() => handleJoin()} disabled={submitting}>
                        {submitting ? 'Joining...' : '🚪 Join House'}
                    </button>

                    {popularHouses.length > 0 && (
                        <div className={styles.popular}>
                            <h3 className="sectionTitle">🏠 My Houses</h3>
                            <div className={styles.popularList}>
                                {popularHouses.map((h) => (
                                    <button
                                        key={h.id}
                                        className={styles.popularCard}
                                        onClick={() => navigate('/')}
                                        disabled={submitting}
                                    >
                                        <div className={styles.popularInfo}>
                                            <span className={styles.popularName}>{h.data.name}</span>
                                            <span className={styles.popularMembers}>{h.data.members.length} members</span>
                                        </div>
                                        <span className={styles.popularJoin}>Open →</span>
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            ) : (
                <div className="section">
                    <div className="inputGroup">
                        <label className="inputLabel">House Name</label>
                        <input
                            className="inputField"
                            placeholder="Our Apartment"
                            value={houseName}
                            onChange={(e) => setHouseName(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleCreate()}
                        />
                    </div>
                    {error && <p className={styles.error}>{error}</p>}
                    <button className="btnPrimary" onClick={handleCreate} disabled={submitting}>
                        {submitting ? 'Creating...' : '🏠 Create House'}
                    </button>
                </div>
            )}

            <button className="btnGhost" onClick={() => navigate('/')} style={{ marginTop: 16, width: '100%', textAlign: 'center', display: 'flex', justifyContent: 'center' }}>
                ← Back to Dashboard
            </button>
        </div>
    );
}
